include = [
    "git::https://github.com/ACHolmes/dotfiles.git//mise-bundles/cloud.toml?ref=main",
    "git::https://github.com/ACHolmes/dotfiles.git//mise-bundles/frontend.toml?ref=main",
    "git::https://github.com/ACHolmes/dotfiles.git//mise-bundles/python.toml?ref=main",
]

[settings]
minimum_release_age = "7d"


