

[settings]


[tasks]

[tasks.setup]
description = "Setup environment (not idempotent rn)"
run = [
    "mkdir -p ~/.config/mise",
    "touch ~/.config/mise/config.toml",
    "cat base-config.toml > ~/.config/mise/config.toml"
]